// flow-typed signature: 2712344c810ad1d754f2b4a629c3c40b
// flow-typed version: <<STUB>>/inferno-redux_v^1.4.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-redux/dist-es/connect' {
  declare module.exports: any;
}

declare module 'inferno-redux/dist-es/helpers' {
  declare module.exports: any;
}

declare module 'inferno-redux/dist-es/index' {
  declare module.exports: any;
}

declare module 'inferno-redux/dist-es/Provider' {
  declare module.exports: any;
}

declare module 'inferno-redux/dist-es/utils' {
  declare module.exports: any;
}

declare module 'inferno-redux/dist/connect' {
  declare module.exports: any;
}

declare module 'inferno-redux/dist/helpers' {
  declare module.exports: any;
}

declare module 'inferno-redux/dist/index' {
  declare module.exports: any;
}

declare module 'inferno-redux/dist/inferno-redux' {
  declare module.exports: any;
}

declare module 'inferno-redux/dist/inferno-redux.min' {
  declare module.exports: any;
}

declare module 'inferno-redux/dist/Provider' {
  declare module.exports: any;
}

declare module 'inferno-redux/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-redux/dist-es/connect.js' {
  declare module.exports: $Exports<'inferno-redux/dist-es/connect'>;
}
declare module 'inferno-redux/dist-es/helpers.js' {
  declare module.exports: $Exports<'inferno-redux/dist-es/helpers'>;
}
declare module 'inferno-redux/dist-es/index.js' {
  declare module.exports: $Exports<'inferno-redux/dist-es/index'>;
}
declare module 'inferno-redux/dist-es/Provider.js' {
  declare module.exports: $Exports<'inferno-redux/dist-es/Provider'>;
}
declare module 'inferno-redux/dist-es/utils.js' {
  declare module.exports: $Exports<'inferno-redux/dist-es/utils'>;
}
declare module 'inferno-redux/dist/connect.js' {
  declare module.exports: $Exports<'inferno-redux/dist/connect'>;
}
declare module 'inferno-redux/dist/helpers.js' {
  declare module.exports: $Exports<'inferno-redux/dist/helpers'>;
}
declare module 'inferno-redux/dist/index.js' {
  declare module.exports: $Exports<'inferno-redux/dist/index'>;
}
declare module 'inferno-redux/dist/inferno-redux.js' {
  declare module.exports: $Exports<'inferno-redux/dist/inferno-redux'>;
}
declare module 'inferno-redux/dist/inferno-redux.min.js' {
  declare module.exports: $Exports<'inferno-redux/dist/inferno-redux.min'>;
}
declare module 'inferno-redux/dist/Provider.js' {
  declare module.exports: $Exports<'inferno-redux/dist/Provider'>;
}
declare module 'inferno-redux/dist/utils.js' {
  declare module.exports: $Exports<'inferno-redux/dist/utils'>;
}
declare module 'inferno-redux/index' {
  declare module.exports: $Exports<'inferno-redux'>;
}
declare module 'inferno-redux/index.js' {
  declare module.exports: $Exports<'inferno-redux'>;
}
